resources:
- name: concourse-release
  type: git
  source:
    uri: https://github.com/xtreme-peter-iskandar/concourse-release-test.git
    branch: master
- name: gh-release
  type: github-release
  source:
    user: xtreme-peter-iskandar
    repository: concourse-release-test
    access_token: {{access-token}}
- name: resource-deploy
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
jobs:
- name: build
  plan:
  - get: concourse-release
  - task: build
    file: concourse-release/ci/tasks/build/build.yml
  - put: gh-release
    params:
      name: releases/name
      tag: releases/tag
      globs:
      - releases/*.jar
- name: deploy
  plan:
    - get: concourse-release
    - get: gh-release
    - put: resource-deploy
      params:
        manifest: release-test/manifests/manifest.yml
      trigger: true
      passed: [build]
    - task: deploy
