resources:
- name: version
  type: semver
  initial_version: 0.0.1
  source:
    driver: git
    uri: https://github.com/xtreme-peter-iskandar/concourse-release-test.git
    branch: master
    file: version/version
- name: concourse-release
  type: git
  source:
    uri: https://github.com/xtreme-peter-iskandar/concourse-release-test.git
    branch: master
- name: gh-release
  type: github-release
  source:
    user: xtreme-peter-iskandar
    repository: concourse-release-test
    access_token: {{access-token}}
jobs:
- name: build
  plan:
  - get: version
    params: {bump: minor}
  - get: concourse-release
  - task: build
    file: concourse-release/ci/tasks/build/build.yml
  - put: gh-release
    params:
      name: releases/name
      tag: releases/tag
      globs:
      - releases/*.jar
  - put: version
    params: {file: version/version}
