resources:
- name: concourse-release
  type: git
  source:
    uri: https://github.com/xtreme-peter-iskandar/concourse-file-test.git
    branch: master
- name: gh-release
  type: github-release
  source:
    owner: xtreme-peter-iskandar
    repository: concourse-file-test
jobs:
- name: build
  plan:
  - get: concourse-release
  - task: build
    file: concourse-release/module/ci/tasks/build/build.yml

