resources:
- name: concourse-release
  type: git
  source:
    uri: https://github.com/xtreme-peter-iskandar/concourse-release-test.git
    branch: master
- name: gh-release
  type: github-release
  source:
    user: xtreme-peter-iskandar
    repository: concourse-release-test
    access_token: {{access-token}}
jobs:
- name: build
  plan:
  - get: concourse-release
  - task: build
    file: concourse-release/ci/tasks/build/build.yml
  - put: gh-release
    params:
      name: releases/name
      tag: releases/tag
      globs:
      - releases/*.jar
- name: deploy
  plan:
    - get: concourse-release
    - get: gh-release
      trigger: true
      passed: [build]
    - task: deploy
      file: concourse-release/ci/tasks/deploy/deploy.yml
      params:
        CF_USERNAME: {{cf-username}}
        CF_PASSWORD: {{cf-password}}
        CF_ORG: {{cf-org}}
        CF_SPACE: {{cf-space}}
